version: "3.9"
services:
  nginx:
    image: mysite_async_nginx
    volumes:
      - socket_data:/tmp/gunicorn/
    ports:
      - "8888:80"
    restart: always
    depends_on:
      - web

  web:
    image: mysite_async_web
    volumes:
      - socket_data:/tmp/gunicorn/
    restart: always

volumes:
  socket_data:
