version: "3.9"
services:
  nginx:
    image: mysite_sync_nginx
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - default

  web:
    image: mysite_sync_web
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
    networks:
      - default
      - my-network

volumes:
  uwsgi_data:

networks:
  my-network:
    external: true
