version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 8001:5432
    networks:
      - my-network

networks:
  my-network:
    external: true